version: '3.6'
services:
  backend:
    env_file:
        ".env"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - "backend:be"
      
  # currently not used
  redis:
    image: "redis:alpine"